name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.yogi109 }}
          password: ${{ secrets.seebeyond}}
      - name: Build Docker image
        run: |
          docker build -t movie-store .
          docker tag movie-store yogi109/movie-store

      - name: Push Docker image
        run: docker push yogi109/movie-store

      # - name: Deploy to Kubernetes
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      #     namespace: your-namespace
      #     manifests: |
      #       your-kubernetes-manifests.yaml
