name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: node -v
      - run: npm --version
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t your-image-name .
      #     docker tag your-image-name your-dockerhub-username/your-image-name

      # - name: Push Docker image
      #   run: docker push your-dockerhub-username/your-image-name

      # - name: Deploy to Kubernetes
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      #     namespace: your-namespace
      #     manifests: |
      #       your-kubernetes-manifests.yaml
